修复文本相似度函数除0报错
MountainDash/nonebot-bison pull request #302
Opened 2023-07-25 13:56 UTC by UKMeng

没有考虑到bilibili的推送出现动态或者视频简介长度为零的情况，出现文本相似度除0Error

2023-07-25 15:31 UTC, AzideCupric commented
记得补个测试

2023-07-26 09:12 UTC, AzideCupric requested changes

2023-07-26 09:12 UTC, AzideCupric commented on nonebot_bison/utils/__init__.py
>  def text_similarity(str1, str2) -> float:
改了text_similarity可以单独测试这个函数
```python
def test_text_similarity_with_text_empty():
    from nonebot_bison.utils import text_similarity
    str1 = ""
    str2 = "xxxx"
    assert text_similarity(str1, str2) == 0.xxxx
```

2023-07-26 12:00 UTC, AzideCupric approved these changes

2023-07-27 04:21 UTC, felinae98 commented on nonebot_bison/utils/__init__.py
> +        return 1.0
为什么返回的是1呢

2023-07-27 05:50 UTC, UKMeng commented on nonebot_bison/utils/__init__.py
> +        return 1.0
因为功能是返回大于0.8时，两字符串判定为相似，取长的那条拼接到text里面。
当其中一条字符串长度为0的时候，实际的效果是舍掉这条长度0的字符串，实际的效果与两字符串判定为相似的效果一致，所以返回1.0。

2023-08-03 01:34 UTC, AzideCupric commented on nonebot_bison/utils/__init__.py
> +    return ""
找不到就raise得了(

2023-08-24 13:46 UTC, felinae98 commented on nonebot_bison/utils/__init__.py
> +def similar_text_process(str1: str, str2: str, custom_comparison: dict[float, Callable[[str, str], str]]):
其实这个函数是不应该存在的，理解这里的意思是用这一个函数代替一个 switch-case 的结构，但是这样做的结果是代码的可读性其实不如 switch case 那么直观（你也知道这一点所以这里用了大段的注释）。
我觉得用 switch case 就挺好的

2023-08-27 02:51 UTC, felinae98 commented on nonebot_bison/platform/bilibili.py
> +    def _text_process(self, dynamic, desc, title) -> str:
```suggestion
    def _text_process(self, dynamic: str, desc: str, title: str) -> str:
```

2023-08-27 02:51 UTC, felinae98 commented on nonebot_bison/platform/rss.py
> +    def _text_process(self, title, desc) -> str:
```suggestion
    def _text_process(self, title: str, desc: str) -> str:
```

2023-08-27 08:27 UTC, felinae98 approved these changes

2023-08-27 08:28 UTC, merged