更详细的微博
MountainDash/nonebot-bison pull request #504
Opened 2024-03-19 10:54 UTC by LambdaYH

2024-03-19 11:52 UTC, AzideCupric requested changes

2024-03-19 11:52 UTC, AzideCupric commented on nonebot_bison/platform/weibo.py
> +            )
转发部分的文本现在可以塞到Post.repost字段里了

2024-03-19 11:52 UTC, AzideCupric commented on tests/platforms/test_weibo.py
对于新的改动部分是不是也可以稍微补一点测试

2024-03-19 11:52 UTC, AzideCupric commented on nonebot_bison/platform/weibo.py
> +                elem.text = f"{elem.text}({url} )"
```suggestion
                elem.text = f"{elem.text}({url})"
```
是不是多了个空格(

2024-03-19 14:00 UTC, LambdaYH commented on nonebot_bison/platform/weibo.py
> +                elem.text = f"{elem.text}({url} )"
如果没空格，')'容易被当作链接的一部分识别（

2024-03-20 12:44 UTC, AzideCupric commented
repost现在还不会渲染，测试可能过不了，你等我开一个pr修一下(乐

2024-03-21 06:18 UTC, AzideCupric commented
> repost现在还不会渲染，测试可能过不了，你等我开一个pr修一下(乐

可以 rebase 一下 main 分支了，这样前端构建应该就不会炸了

2024-03-21 11:08 UTC, AzideCupric approved these changes

2024-03-21 15:41 UTC, felinae98 commented
能够获取到视频微博的视频 cover 吗

2024-03-25 11:05 UTC, felinae98 approved these changes

2024-03-25 11:06 UTC, merged