🐛 B站蹲饼修复
MountainDash/nonebot-bison pull request #525
Opened 2024-04-08 12:14 UTC by AzideCupric

代价是要常驻Browser了

2024-04-08 12:14 UTC, AzideCupric commented
#511

2024-04-14 08:04 UTC, felinae98 approved these changes

2024-04-14 08:04 UTC, felinae98 commented on nonebot_bison/platform/bilibili/scheduler.py
> +        return cookies
这里是不是应该放在 Scheduler 里面

2024-04-18 04:32 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/scheduler.py
> +        return cookies
塞进scheduler里好像不好调用刷新函数了

2024-06-11 05:18 UTC, felinae98 commented on nonebot_bison/platform/bilibili/models.py
> +DynamicType = Literal[
enum?

2024-06-11 05:18 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +            # {
?

2024-06-11 05:18 UTC, felinae98 commented on nonebot_bison/platform/bilibili/scheduler.py
> +        browser = await get_browser()
这里会有并发控制吗？同时最多运行几个浏览器这样

2024-06-11 05:18 UTC, felinae98 commented on nonebot_bison/platform/bilibili/scheduler.py
> +        await page.close()
这里能不能用 with page: 保证 page 可以关掉

2024-06-11 05:18 UTC, felinae98 commented on nonebot_bison/utils/__init__.py
> +def decode_escapes(s: str):
```suggestion
def decode_unicode_escapes(s: str):
```

2024-06-11 05:23 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/models.py
> +DynamicType = Literal[
没必要enum吧 这是B站的json里的内容，ide对Literal的补全也挺好的其实(

2024-06-11 05:25 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/platforms.py
> +            # {
这个desc的结构示例，他的字段不怎么固定，这里放个需要的部分

2024-06-11 05:25 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/scheduler.py
> +        browser = await get_browser()
`get_browser()`会获取htmlrender里那个全局实例

2024-06-11 15:26 UTC, felinae98 commented on nonebot_bison/platform/bilibili/scheduler.py
> +        await page.close()
这个地方确定过 page 的 __aexit__() 可以关闭 page 吗

2024-06-11 15:47 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +                logger.debug(f"用户{target}的动态列表: {':'.join(x.id_str or x.basic.rid_str for x in items)}")
logger.trace 吧

2024-06-11 15:47 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +            logger.debug(f"获取用户{target}的动态列表成功，但是没有动态")
ditto

2024-06-11 15:47 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +            return dyn.desc.text if dyn.desc else ""
这两个能不能直接算出来，就不用函数了

2024-06-11 15:47 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
>          class ParsedPost(NamedTuple):
这个为什么会定义在函数里

2024-06-11 15:47 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +    def _major_parser(self, raw_post: DynRawPost):
把 ParsedPost 拿出来，在 type hinting 里加上吧，然后换个名字？pre_parse 这样的

2024-06-11 17:57 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/scheduler.py
> +        await page.close()
有的
![image](https://github.com/MountainDash/nonebot-bison/assets/57004769/0b08f91d-454b-4732-86b4-b0e9e13cedf1)

2024-06-11 17:58 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/scheduler.py
> +        await page.close()
坏 怎么close我还留着（

2024-06-11 17:59 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/platforms.py
> +            return dyn.desc.text if dyn.desc else ""
因为好几个地方都用到了，就统一放在这里了

2024-06-11 18:04 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/platforms.py
>          class ParsedPost(NamedTuple):
只需要他的提示补全而不需要复用他，所以就定义在了函数内部（有个地方看到过但是具体忘记在哪了

2024-06-11 18:07 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/platforms.py
> +            return dyn.desc.text if dyn.desc else ""
`make_common_dynamic_url`之前更复杂一点，现在倒是可以改回去

2024-06-11 18:12 UTC, AzideCupric commented on nonebot_bison/platform/bilibili/platforms.py
> +    def _major_parser(self, raw_post: DynRawPost):
取名叫mojar_parse是因为他就是根据mojar字段来分发处理的，我觉得这个名字不太需要换(

2024-06-12 15:18 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +    def _major_parser(self, raw_post: DynRawPost):
parse_by_major 吧

2024-06-12 15:18 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
>          class ParsedPost(NamedTuple):
拿出来吧，看着还是太怪了

2024-06-12 15:18 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +        class _ProcessedText(NamedTuple):
这个也拿出来吧

2024-06-12 18:22 UTC, AzideCupric commented
哈哈 github actions炸了 下工！

2024-06-13 05:25 UTC, AzideCupric commented
好的 过了

2024-06-13 07:53 UTC, felinae98 commented
action 相关的新开个 pr 吧

2024-06-13 07:54 UTC, AzideCupric commented
昨晚action崩了随便试试的

2024-06-16 09:54 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +                raise ApiError(e.args[0])
这坨能不能用现成的 retry 库

2024-06-16 09:59 UTC, felinae98 commented on nonebot_bison/platform/bilibili/platforms.py
> +                logger.success("已尝试刷新cookie")
```suggestion
```

2024-06-17 04:52 UTC, felinae98 approved these changes

2024-06-17 04:56 UTC, felinae98 requested changes

2024-06-17 04:56 UTC, felinae98 commented on nonebot_bison/platform/bilibili/scheduler.py
> +class BilibiliSite(Site):
这里有个 require_browser 要设成 true

2024-06-17 05:10 UTC, felinae98 commented on nonebot_bison/platform/bilibili/scheduler.py
> +    client_mgr = BilibiliClientManager
```suggestion
    client_mgr = BilibiliClientManager
    require_browser = true
```

2024-06-17 05:24 UTC, merged