refactor client getting logic in platform config
MountainDash/nonebot-bison pull request #544
Opened 2024-05-28 13:02 UTC by felinae98

* split ClientManager from PlatformConfig
* move ClientManager into context

2024-05-28 13:41 UTC, AzideCupric requested changes

2024-05-28 13:41 UTC, AzideCupric commented on nonebot_bison/scheduler/scheduler.py
> +    client_man: ClientManager
还是不要缩写吧

2024-05-28 13:41 UTC, AzideCupric commented on nonebot_bison/utils/context.py
> +    def __init__(self, client_man: ClientManager) -> None:
这里的变量名缩写也是

2024-05-28 13:41 UTC, AzideCupric commented on nonebot_bison/utils/scheduler_config.py
> +    client_man: type[ClientManager] = DefaultClientManager
这里的变量名缩写也是

2024-05-28 13:41 UTC, AzideCupric commented on nonebot_bison/utils/scheduler_config.py
> +            "client_man": ClientManager,
这里的缩写

2024-06-02 14:56 UTC, AzideCupric requested changes

2024-06-02 14:56 UTC, AzideCupric commented on nonebot_bison/utils/site.py
> +def site(schedule_type: Literal["date", "interval", "cron"], schedule_setting: dict) -> type[Site]:
这个有用到吗？或许叫`make_site`比较好？

2024-06-02 15:04 UTC, felinae98 commented on nonebot_bison/utils/site.py
> +def site(schedule_type: Literal["date", "interval", "cron"], schedule_setting: dict) -> type[Site]:
ff14用到了

2024-06-02 15:05 UTC, felinae98 commented on nonebot_bison/utils/site.py
> +def site(schedule_type: Literal["date", "interval", "cron"], schedule_setting: dict) -> type[Site]:
anonymous_site ?

2024-06-03 07:54 UTC, AzideCupric commented on nonebot_bison/utils/site.py
> +def site(schedule_type: Literal["date", "interval", "cron"], schedule_setting: dict) -> type[Site]:
simple_site? anonymous_site也行吧（就是有点长

2024-06-03 07:55 UTC, AzideCupric approved these changes

2024-06-03 10:36 UTC, merged