:sparkles: `post` 新增 `get_content()` 方法
MountainDash/nonebot-bison pull request #553
Opened 2024-06-08 09:48 UTC by GuGuMur

fix #526

~图片直接删 爽！~

2024-06-12 15:22 UTC, felinae98 commented
可以搞成
```python
@property
def content():
```
可以少改很多

2024-06-12 15:23 UTC, felinae98 commented
当然已经改了就算了

2024-06-12 17:34 UTC, AzideCupric commented
考虑尽可能保留content内的信息比较好，毕竟有些富文本格式在某些theme内是可以使用的

希望是可以有一个
```python
@property
def plain_content(self):
	...
```
然后不同的theme按需选择使用`content`还是`plain_content`，这样好一点。

但目前有个问题，`Post` 和 `Platform` 基本上是独立的，每个 `Platform` 对应的 `plain_content` 的提取行为显然不可能完全一样，如何把 `Platform` 生成 `plain_content` 的这个行为放进 `Post` 里是需要考虑的。~同时我不喜欢在Platform里蹦出来一个对`Post`的继承~

得益于函数是一等公民的好处，或许可以有这样的一种实现
```python

class APlatform(NewMessage):
	#...

	async def parse(...):
		def _get_plain_content(content: str):
			# 诸如正则之类的提取
			return plain_content
		
		# 1
		post = Post(
			# ...
			plain_content_func = _get_plain_content
			)
		# 2
		post.register_plain_content_func(_get_plain_content)
		return post
```
在原有的Post中添加
```python
class Post(...):
	plain_content_func: Callable[...] | None = None
	
	def __init__(..., plain_content_func: Callable[...] | None = None):
		self.plain_content_func = plain_content_func
	
	def register_plain_content_func(self, func: Callable[...]):
		self.plain_content_func = func
	
	@property
	def plain_content(self):
		if self.plain_content_func:
			return self.plain_content_func(self.content)
		return self.content
```
类似这样的实现方案

2024-06-16 06:52 UTC, AzideCupric requested changes

2024-06-16 06:52 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +            if class_field.name in ("content", "platform", "repost", "content_handlers"):
里可以把有哪些theme的handler打印出来

2024-06-16 06:52 UTC, AzideCupric commented on nonebot_bison/theme/types.py
> +        content_handler = post.content_handlers.get(self.name, None)
不需要在这里拿出来再传进去啊，在各个theme的render函数里再拿就好吧
毕竟你拿出来他也还是在传进去的post里

2024-06-16 06:56 UTC, AzideCupric commented on nonebot_bison/theme/types.py
> +        content_handler = post.content_handlers.get(self.name, None)
可以给post写一个`get_content_handler(theme_name)`
在theme的render函数里调用
```python
async def render(self, post):
	content_handler = post.get_content_handler(self.name)
	...
```

2024-06-16 07:18 UTC, AzideCupric requested changes

2024-06-16 07:18 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +
```suggestion
    async def get_content_handler(self, theme_name: str) -> Callable[[str], Awaitable[str]] | None:
        """获取主题对应的content处理函数"""
        if handler := self.content_handlers.get(theme_name):
        	return await handler(self.content)
        return self.content
```

2024-06-16 07:18 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +
```suggestion
    async def get_content(self, theme_name: str) -> Callable[[str], Awaitable[str]] | None:
        """获取主题对应的content处理函数"""
        if handler := self.content_handlers.get(theme_name):
        	return await handler(self.content)
        return self.content
```

2024-06-16 07:18 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +            if class_field.name in ("content", "platform", "repost"):
我是指只用打印handlers的key不用打印value(

2024-06-16 07:18 UTC, AzideCupric commented on nonebot_bison/theme/types.py
> +    async def is_support_render(self, post: "Post") -> bool:
这里原来是`"AbstractPost"`

2024-06-16 07:19 UTC, AzideCupric commented on nonebot_bison/theme/types.py
> +    async def is_support_render(self, post: "Post") -> bool:
还有其他的地方也没改回来(

2024-06-16 07:23 UTC, GuGuMur commented on nonebot_bison/theme/types.py
> +    async def is_support_render(self, post: "Post") -> bool:
但是`AbstractPost`没有`content_handlers`这个属性啊（

2024-06-16 07:24 UTC, AzideCupric commented on nonebot_bison/theme/types.py
> +    async def is_support_render(self, post: "Post") -> bool:
上面改成get_content方法了(

2024-06-16 07:25 UTC, GuGuMur commented on nonebot_bison/theme/types.py
> +    async def is_support_render(self, post: "Post") -> bool:
oh

2024-06-16 07:26 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +
参考猫猫的review，直接用 @property def content 可行吗

2024-06-16 07:49 UTC, GuGuMur commented on nonebot_bison/post/post.py
> +
难保以后会不会出现联网处理函数的情况 摆了（

2024-06-16 08:04 UTC, AzideCupric approved these changes

2024-06-16 09:19 UTC, felinae98 commented
还是 plain_content() 吧））

2024-06-18 16:07 UTC, AzideCupric commented
还是 plain_content 吧，考虑了一下应该很难用得着这么复杂的情况

2024-06-22 14:28 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +    plain_content_handler: Callable[[str], str] | None = None
能不能用数据类的特性，用一个类变量dict存每个platform的plain_content_handlers，然后用一个类装饰器将那个函数注册进来，因为Post实例里是存有一个platform的实例的，这样plain_content里可以获取到这个platform的名称，调用到对应的处理函数

2024-06-22 14:30 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +    plain_content_handler: Callable[[str], str] | None = None
然后提供一个默认空的custom_plain_content_handler（好长
用来为单个post实例覆盖默认的处理行为

2024-06-22 14:31 UTC, GuGuMur commented on nonebot_bison/post/post.py
> +    plain_content_handler: Callable[[str], str] | None = None
那不就跟最开始的 content_handlers 一个效果了（

2024-06-22 14:33 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +    plain_content_handler: Callable[[str], str] | None = None
> 那不就跟最开始的 content_handlers 一个效果了（

现在不需要theme

2024-06-23 07:21 UTC, AzideCupric requested changes
印象里微博那边也带点html标签的，能不能也挪进来

2024-06-23 07:21 UTC, AzideCupric commented on nonebot_bison/platform/arknights.py
> +def content_handler(content: str) -> str:
能不能用beautifulsoup提取，正则有点多了(

2024-06-23 07:21 UTC, AzideCupric commented on nonebot_bison/post/post.py
> +            elif cls_field.name == "content_handlers":
这里没改

2024-06-23 07:23 UTC, AzideCupric commented on nonebot_bison/theme/themes/ht2i/build.py
ht2i似乎是容许html标签的，感觉可以不去掉？

2024-06-23 08:52 UTC, AzideCupric approved these changes

2024-07-11 14:48 UTC, felinae98 commented
Post 的定义不应该变，应该新搞一个 HTMLPost 继承 Post，里面有一个 html_content 的字段。
platform 返回 HTMLPost，theme 检查这个 post 是不是 htmlpost

2024-07-22 05:19 UTC, GuGuMur commented
（挠头）这么一来，是不是还得整个 MarkdownPost 什么的啊（

~~yysy 早知道中间折腾下这么多版本，群友说法一个星期一遍，一开始就写 plain_content 了，折腾什么装饰器什么函数啊~~

~~启示各位处理pr要趁早，拖的越久越解决不了~~

2024-07-24 04:26 UTC, AzideCupric commented
新写的Demo
```python
# post.py
from functools import partial
from typing import Protocol, runtime_checkable
from dataclasses import dataclass

@dataclass
class Post:
    title: str
    content: str

@runtime_checkable
class PlainContentSupport(Protocol):
    async def get_plain_content(self) -> str:
        ...

@runtime_checkable
class HTMLContentSupport(Protocol):
    async def get_html_content(self) -> str:
        ...

@runtime_checkable
class MarkdownContentSupport(Protocol):
    async def get_markdown_content(self) -> str:
        ...


# platform
## bilibili.py
class BilibiliPost(Post, PlainContentSupport, HTMLContentSupport):
    async def get_plain_content(self) -> str:
        return self.content

    async def get_html_content(self) -> str:
        return f"<p>{self.content}</p>"

class Bilibili:
    def parse(self) -> BilibiliPost:
        return BilibiliPost(title="蒙古上单", content="柠檬什么时候熟啊")

## weibo.py
class WeiboPost(Post):
    async def get_markdown_content(self) -> str:
        return f"**{self.content}**"

class Weibo:
    def parse(self) -> WeiboPost:
        return WeiboPost(title="1+1", content="芝士雪豹")

## ncm.py
class Ncm:
    def parse(self) -> Post:
        return Post(title="塞壬唱片", content="发布了新专辑")

# theme.py
class PlainTheme:
    async def render(self, post: Post) -> str:
        if isinstance(post, PlainContentSupport):
            content = await post.get_plain_content()
        else:
            content = post.content

        return f"{post.title}\n{content}"

class RichTheme:
    async def render(self, post: Post) -> str:
        if isinstance(post, HTMLContentSupport):
            content = await post.get_html_content()
        else:
            content = post.content

        return f"<title>{post.title}<title>\n{content}"

class MarkdownTheme:
    async def render(self, post: Post) -> str:
        if isinstance(post, MarkdownContentSupport):
            content = await post.get_markdown_content()
        elif isinstance(post, HTMLContentSupport):
            content = await post.get_html_content()
        else:
            content = post.content

        return f"# {post.title}\n\n{content}"


if __name__ == "__main__":
    bilibili = Bilibili().parse()
    weibo = Weibo().parse()
    ncm = Ncm().parse()

    plain_theme = PlainTheme()
    rich_theme = RichTheme()
    markdown_theme = MarkdownTheme()

    _print = partial(print, end="\n\n---\n\n")

    async def main():
        _print(await plain_theme.render(bilibili))
        _print(await rich_theme.render(bilibili))
        _print(await markdown_theme.render(bilibili))

        _print(await plain_theme.render(weibo))
        _print(await rich_theme.render(weibo))
        _print(await markdown_theme.render(weibo))

        _print(await plain_theme.render(ncm))
        _print(await rich_theme.render(ncm))
        _print(await markdown_theme.render(ncm))

    import asyncio
    asyncio.run(main())
```

2024-07-29 12:12 UTC, felinae98 commented on nonebot_bison/platform/rss.py
> +        return self.content
这里不确定能不能这样，rss 是 xml，和 html 不完全一样

2024-07-29 12:12 UTC, felinae98 commented on nonebot_bison/theme/themes/ht2i/build.py
> +            content = post.content
这里应该是 get_plain_content?

2024-07-29 12:17 UTC, AzideCupric commented on nonebot_bison/platform/arknights.py
> +class ArknightsPost(Post, HTMLContentSupport):
`PlainContentSupport`是Post的内置抽象方法

2024-07-29 12:26 UTC, AzideCupric commented on nonebot_bison/platform/rss.py
> +        return self.content
好像确实不太...

2024-07-29 13:05 UTC, GuGuMur commented on nonebot_bison/theme/themes/ht2i/build.py
> +            content = post.content
> #400 ：`html-render-text-to-image`

应该是用HTML渲染吧（

2024-07-30 03:47 UTC, felinae98 commented on nonebot_bison/post/support.py
> +
这里建议不要提供 XMLContent，因为所谓 XML content 不是一种确切定义的格式，在处理 rss 的时候应该只返回 plain

2024-07-30 03:47 UTC, felinae98 commented on nonebot_bison/theme/themes/ht2i/build.py
> +            content = post.content
这里考虑的是应该使用 post 中定义好的方法访问 post 中的内容，content 现在已经是 post 中的私有内容了，不应该直接通过访问 content 来获取这个内容

2024-07-30 05:28 UTC, felinae98 approved these changes

2024-07-31 14:50 UTC, AzideCupric commented
@GuGuMur 改一下title就能合了

2024-08-04 10:39 UTC, merged