:bug: 查询订阅时提示不存在的平台 fix #515
MountainDash/nonebot-bison pull request #584
Opened 2024-06-27 03:32 UTC by suyiiyii

2024-06-27 09:09 UTC, felinae98 commented on nonebot_bison/sub_manager/del_sub.py
> +                res += "\n"
else 一下吧，提示一下这个 platform 不存在了

2024-06-27 13:16 UTC, AzideCupric requested changes

2024-06-27 13:16 UTC, AzideCupric commented on tests/sub_manager/test_query_del.py
> +                + "1 weibo 明日方舟Arknights 6279793937"
为什么要把换行删了，原来的分列两行的设计有什么问题吗(

2024-06-27 13:40 UTC, suyiiyii commented on tests/sub_manager/test_query_del.py
> +                + "1 weibo 明日方舟Arknights 6279793937"
原来的查询是不换行的，删除是换行的。就把两边都规范成不换行的了（

2024-06-27 13:52 UTC, AzideCupric commented on tests/sub_manager/test_query_del.py
> +                + "1 weibo 明日方舟Arknights 6279793937"
感觉统一都换行好一点？qq自己的换行指不定从哪开始换（

2024-06-27 16:20 UTC, AzideCupric approved these changes

2024-07-02 16:10 UTC, felinae98 approved these changes

2024-07-03 02:26 UTC, merged