:sparkles: 添加简单统计功能
MountainDash/nonebot-bison pull request #661
Opened 2024-12-04 15:46 UTC by AzideCupric

2024-12-05 04:43 UTC, suyiiyii requested changes
sample:
```
新增订阅hook调用记录:
删除订阅hook调用记录:
调度统计:
  weibo:
    792958: 1266 次
    794708: 1265 次
  arknights:
    default: 254 次
  bilibili:
    354678198: 127 次
发送消息统计:
  明日方舟游戏信息:
    2 次
所有调度对象:
  arknights:
    default: [权重]0 | [批量]False
  bilibili.com:
    354678198: [权重]0 | [批量]False
  live.bilibili.com:
  bilibili.com/bangumi:
  ceobe_canteen:
  AnonymousScheduleConfig[ff14]:
  music.163.com:
  rss:
  weibo.com:
    792958: [权重]-10 | [批量]False
    794708: [权重]10 | [批量]False
```

「所有调度对象」里面，某一项，如果是空的，是不是可以不输出这一项  （或者加个选项？

2024-12-05 08:07 UTC, felinae98 commented
说实话，这个该用 metrics 来做

2024-12-05 10:34 UTC, AzideCupric commented on nonebot_bison/config/db_config.py
> +                hook_resp = await asyncio.gather(*[hook(platform_name, target) for hook in self.add_target_hook])
hook func的返回值 虽然目前为空就是了（

2025-01-05 15:58 UTC, AzideCupric commented
由 #666 完成

2025-01-05 15:58 UTC, closed without merging