:technologist: 使用 Ruff 包办所有格式化和检查
MountainDash/nonebot-bison pull request #663
Opened 2024-12-11 15:44 UTC by AzideCupric

除了静态类型检查(

2024-12-12 01:46 UTC, he0119 approved these changes

2024-12-12 02:41 UTC, suyiiyii requested changes
https://github.com/MountainDash/nonebot-bison/blob/a084ed0c93d09eca3add9b37dc81f961c6001112/README.md#L20-L22

那 black 的 badge 是不是可以去掉了

2024-12-16 16:56 UTC, suyiiyii approved these changes

2024-12-17 02:51 UTC, felinae98 approved these changes

2024-12-17 02:52 UTC, merged