✨ 增加 Metric 服务
MountainDash/nonebot-bison pull request #666
Opened 2024-12-16 14:21 UTC by suyiiyii

resolve #105

2024-12-21 02:11 UTC, he0119 commented on nonebot_bison/metrics.py
> +from prometheus_client import Gauge, Counter, Histogram
说起来为什么不是从插件导入呢（

2024-12-21 02:13 UTC, he0119 commented on pyproject.toml
> +prometheus-client = "^0.21.0"
这样就不需要这个依赖了。

2024-12-24 16:00 UTC, AzideCupric commented
是不是得补充一点用户使用文档
怎么打开和接入之类的

2024-12-24 16:03 UTC, suyiiyii commented
别急（
不合进去都不好写 compose.yaml
不过，会用 Prometheus 和 Grafana 的，也不需要教吧（
晚点再起一个 pr 写文档和 compose.yaml 吧

2024-12-24 16:07 UTC, AzideCupric commented
> 会用 Prometheus 和 Grafana 的，也不需要教吧（ 

倒也不用写很细致，就是让用户知道这回事和介绍一下基本的接入方式就行

> 晚点再起一个 pr 写文档和 compose.yaml 吧

文档放一起吧 没必要另起pr

2025-01-20 04:37 UTC, felinae98 reviewed
感觉可以添加一下成功或者失败的请求的统计

2025-01-20 04:49 UTC, suyiiyii commented
> 感觉可以添加一下成功或者失败的请求的统计

有的，通过 `request_counter `的 `success` label 来统计

https://github.com/MountainDash/nonebot-bison/blob/07021a026cd3ce124de04850d15058be8f761fd9/nonebot_bison/scheduler/scheduler.py#L109-L116

2025-03-03 12:24 UTC, felinae98 requested changes
> Reviewed 8 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MountainDash/nonebot-bison/666)* status: 8 of 14 files reviewed, 4 unresolved discussions (waiting on @AzideCupric, @he0119, and @suyiiyii)

___
*[`nonebot_bison/scheduler/scheduler.py` line 68 at r2](https://reviewable.io/reviews/MountainDash/nonebot-bison/666#-OKQxPAR0RZRMiygrfhO:-OKQxPAR0RZRMiygrfhP:b-i3snpr) ([raw file](https://github.com/MountainDash/nonebot-bison/blob/07021a026cd3ce124de04850d15058be8f761fd9/nonebot_bison/scheduler/scheduler.py#L68)):*
> ```Python
>         self.platform_name_list = platform_name_list
>         self.pre_weight_val = 0  # 轮调度中“本轮”增加权重和的初值
>         self.metrics_report: Callable[[bool], None] | None = None  # 作为函数变量，允许外部调用来上报此次抓取是否成功
> ```

为啥这个要搞成成员变量
___
*[`docker/grafana-dashboard.json` line 1 at r2](https://reviewable.io/reviews/MountainDash/nonebot-bison/666#-OKQwCUGC1o2sO4ZQx2x:-OKQwCUGC1o2sO4ZQx2y:b-xum21f) ([raw file](https://github.com/MountainDash/nonebot-bison/blob/07021a026cd3ce124de04850d15058be8f761fd9/docker/grafana-dashboard.json#L1)):*
> ```JSON
> {
> ```

这个可以 publish 到 grafana 的 dashboard registry 吗


<!-- Sent from Reviewable.io -->

2025-03-05 12:01 UTC, felinae98 requested changes
> *[Reviewable](https://reviewable.io/reviews/MountainDash/nonebot-bison/666)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @AzideCupric, @he0119, and @suyiiyii)

___
*[`nonebot_bison/scheduler/scheduler.py` line 68 at r2](https://reviewable.io/reviews/MountainDash/nonebot-bison/666#-OKQxPAR0RZRMiygrfhO:-OKa9kT94hgj-5IPS62v:b6kmwks) ([raw file](https://github.com/MountainDash/nonebot-bison/blob/07021a026cd3ce124de04850d15058be8f761fd9/nonebot_bison/scheduler/scheduler.py#L68)):*
<details><summary><i>Previously, felinae98 wrote…</i></summary><blockquote>

为啥这个要搞成成员变量
</blockquote></details>

我觉得这个地方的定义还是纯粹一点吧，仅统计「发出去的请求」的成功还是失败，如果把根本没有产生的网络请求记为失败我觉得这个定义就没有那么清晰了
___
*[`nonebot_bison/scheduler/scheduler.py` line 27 at r2](https://reviewable.io/reviews/MountainDash/nonebot-bison/666#-OKa8X2r4shQ1iBKusdI:-OKa8X2r4shQ1iBKusdJ:b-v59gy2) ([raw file](https://github.com/MountainDash/nonebot-bison/blob/07021a026cd3ce124de04850d15058be8f761fd9/nonebot_bison/scheduler/scheduler.py#L27)):*
> ```Python
> 
> 
> def handle_time_exceeded(event):
> ```

这个地方有一个假设是，造成超时的原因一定是因为网络，万一是因为浏览器渲染超时了这里是不是会错误地记一次失败的网络请求。


<!-- Sent from Reviewable.io -->

2025-03-10 12:22 UTC, suyiiyii commented
> 这个变量不需要了吧

![图片](https://github.com/user-attachments/assets/ff14db8f-64c8-4aa3-80ae-b785a4dd446e)

要不还是带上？不然后面六行的 request_counter.labels().inc() 就要重复写了

2025-03-10 15:43 UTC, felinae98 requested changes
> *[Reviewable](https://reviewable.io/reviews/MountainDash/nonebot-bison/666)* status: 6 of 14 files reviewed, 6 unresolved discussions (waiting on @AzideCupric, @he0119, and @suyiiyii)

___
*[`nonebot_bison/scheduler/scheduler.py` line 129 at r4](https://reviewable.io/reviews/MountainDash/nonebot-bison/666#-OL-i5hdCWPLRcPzoSNh:-OL-i5hdCWPLRcPzoSNi:bv5zixd) ([raw file](https://github.com/MountainDash/nonebot-bison/blob/6f44db4b3c3a484a9de9ecb5c1298493a9a81cf8/nonebot_bison/scheduler/scheduler.py#L129)):*
> ```Python
>             target=schedulable.target,
>             success=success_flag,
>         ).inc()
> ```

这个是不是放在 except .. else 的块里，不然上面抛出错误下面的 counter 也会被跳过


<!-- Sent from Reviewable.io -->

2025-03-11 01:15 UTC, suyiiyii commented
> 这个是不是放在 except .. else 的块里，不然上面抛出错误下面的 counter 也会被跳过

啊？是我看错了么

request_counter 和上面的 try 是同级的吧，预期中会抛出异常的代码都放在 try 块里面了，主体逻辑应该都会被执行的吧😲
假如放在 except .. else 块里，如果抛出了异常，那 request_counter 就不会被执行了吧

另，Grafana dashboard 已上传 https://grafana.com/grafana/dashboards/23053

2025-03-11 02:03 UTC, felinae98 commented
> 啊？是我看错了么
> 
> request_counter 和上面的 try 是同级的吧，预期中会抛出异常的代码都放在 try 块里面了，主体逻辑应该都会被执行的吧😲 假如放在 except .. else 块里，如果抛出了异常，那 request_counter 就不会被

脑子瓦特了，忽略吧

2025-03-11 11:52 UTC, merged