♻️ 迁移到 uv 并重写 Dockerfile
MountainDash/nonebot-bison pull request #667
Opened 2024-12-19 15:56 UTC by AzideCupric

2024-12-20 05:46 UTC, suyiiyii requested changes

2024-12-20 05:46 UTC, suyiiyii commented on docker/Dockerfile
> +RUN --mount=type=cache,target=/var/cache/apt \
把这个 apt-get 的移动到 uv sync 上面吧，似乎 python 依赖变动更频繁一些
或者参照 这个 
https://github.com/suyiiyii/DSExpDesign/blob/d64e1fdf7d3f76e93c6fe60612675ed10a9bacce/Dockerfile#L26-L41 
给他分阶段构建了

btw, action 不支持 --mount=type=cache 这种类型的缓存，不过当前也没有什么影响就是了

2024-12-20 07:43 UTC, he0119 commented on docker/Dockerfile
> +RUN --mount=type=cache,target=/var/cache/apt \
https://github.com/MountainDash/nonebot-bison/blob/c8df2b3cc26d28b919d063b3725cc0a4dbb0a1e0/.github/workflows/release.yml#L100-L101

https://docs.docker.com/build/ci/github-actions/cache/#github-cache

看了一下 cache 应该是开着的，这种写法没问题。

2024-12-23 17:22 UTC, suyiiyii approved these changes

2024-12-24 07:40 UTC, felinae98 commented on docker/Dockerfile
> +COPY nonebot_bison/ /app/nonebot_bison/
extra_plugins 是否需要

2024-12-24 16:11 UTC, AzideCupric commented on .devcontainer/devcontainer.json
> +  "postCreateCommand": "uv venv && uv sync --all-groups --all-extras && uv run pre-commit install && npm install -g pnpm && pnpm install",
docker组可以不用装进来
那个是构建docker的时候单独装的

2024-12-24 16:12 UTC, AzideCupric commented on .dockerignore
> +#*.yaml
这些注释就直接删掉罢

2024-12-24 16:27 UTC, AzideCupric commented on docker/Dockerfile
> +    corepack prepare pnpm@9.15.1 --activate && \
要在这里写死pnpm版本吗

2024-12-24 16:31 UTC, AzideCupric commented on docker/Dockerfile
> +    uv pip install --extra=docker --requirement pyproject.toml --no-cache && \
这里应该不会把dev依赖装上的吧

2024-12-31 04:54 UTC, felinae98 commented on .dockerignore
> +#*.yaml
删了吗

2025-01-03 05:31 UTC, felinae98 commented on .dockerignore
> +# *.yaml
这些注释也去掉吧

2025-01-03 07:55 UTC, felinae98 commented on docker/Dockerfile
> +    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
为什么这个地方使用 bind 而不 copy 进去

2025-01-03 07:55 UTC, felinae98 commented on CHANGELOG.md
> +- :bug: 修复新版 httpx 中 proxy 不起效的问题 [@suyiiyii](https://github.com/suyiiyii) ([#669](https://github.com/MountainDash/nonebot-bison/pull/669))
whats that

2025-01-03 09:55 UTC, merged